/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.antinsa.gui;

import br.edu.utfpr.cm.antinsa.configuration.GDUtils;
import br.edu.utfpr.cm.antinsa.googledrive.GoogleDriveOAuth;
import br.edu.utfpr.cm.antinsa.configuration.Config;
import br.edu.utfpr.cm.antinsa.googledrive.GoogleDriveController;
import br.edu.utfpr.cm.antinsa.security.KeyManager;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.security.InvalidKeyException;
import java.security.KeyManagementException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class JFramePreferences extends javax.swing.JFrame {

    /**
     * Creates new form JFramePreferences
     */
    private TaskBar task;
    private GoogleDriveController driveController;
    private Thread thread;

    public JFramePreferences() {
        try {
            this.task = new TaskBar("icon.png", this, "AntiNSA");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
        task.instanceTask();
        getConfigGoogleDriveAccount();
        jTextFieldDefaultLocation.setText(Config.STORE_DEFAULT.getAbsolutePath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanelGeneral2 = new javax.swing.JPanel();
        jLabelLocation = new javax.swing.JLabel();
        jTextFieldDefaultLocation = new javax.swing.JTextField();
        jPanelAccount = new javax.swing.JPanel();
        jTabbedPaneAccount = new javax.swing.JTabbedPane();
        jPanelGoogleDrive = new javax.swing.JPanel();
        jCheckBoxEnableGoogle = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAuth = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jButtonDeleteAccount = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButtonCopyKey = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelFiles = new javax.swing.JPanel();
        jPanelAbout = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AntiNSA");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabelLocation.setText("Default location:");

        jTextFieldDefaultLocation.setEnabled(false);

        javax.swing.GroupLayout jPanelGeneral2Layout = new javax.swing.GroupLayout(jPanelGeneral2);
        jPanelGeneral2.setLayout(jPanelGeneral2Layout);
        jPanelGeneral2Layout.setHorizontalGroup(
            jPanelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneral2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDefaultLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanelGeneral2Layout.setVerticalGroup(
            jPanelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneral2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneral2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocation)
                    .addComponent(jTextFieldDefaultLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("General", jPanelGeneral2);

        jPanelGoogleDrive.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanelGoogleDrive.setPreferredSize(new java.awt.Dimension(612, 364));

        jCheckBoxEnableGoogle.setText("Enable Google Drive Account");
        jCheckBoxEnableGoogle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxEnableGoogleItemStateChanged(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("E-mail:");

        jButtonAuth.setText("Authenticate");
        jButtonAuth.setMaximumSize(new java.awt.Dimension(97, 34));
        jButtonAuth.setMinimumSize(new java.awt.Dimension(97, 34));
        jButtonAuth.setPreferredSize(new java.awt.Dimension(97, 33));
        jButtonAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthActionPerformed(evt);
            }
        });

        jButtonDeleteAccount.setText("Delete Account");
        jButtonDeleteAccount.setMaximumSize(new java.awt.Dimension(116, 34));
        jButtonDeleteAccount.setMinimumSize(new java.awt.Dimension(116, 34));
        jButtonDeleteAccount.setPreferredSize(new java.awt.Dimension(116, 34));
        jButtonDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAccountActionPerformed(evt);
            }
        });

        jButtonCopyKey.setText("Save your key");
        jButtonCopyKey.setMaximumSize(new java.awt.Dimension(72, 34));
        jButtonCopyKey.setMinimumSize(new java.awt.Dimension(72, 34));
        jButtonCopyKey.setPreferredSize(new java.awt.Dimension(72, 33));
        jButtonCopyKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyKeyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Click this button to save your cryptographic key.");

        javax.swing.GroupLayout jPanelGoogleDriveLayout = new javax.swing.GroupLayout(jPanelGoogleDrive);
        jPanelGoogleDrive.setLayout(jPanelGoogleDriveLayout);
        jPanelGoogleDriveLayout.setHorizontalGroup(
            jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                .addGroup(jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxEnableGoogle)
                    .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                                .addComponent(jButtonAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                .addGroup(jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCopyKey, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelGoogleDriveLayout.setVerticalGroup(
            jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoogleDriveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxEnableGoogle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGoogleDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCopyKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        jTabbedPaneAccount.addTab("Google Drive", jPanelGoogleDrive);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jTabbedPaneAccount.addTab("DropBox", jPanel2);

        javax.swing.GroupLayout jPanelAccountLayout = new javax.swing.GroupLayout(jPanelAccount);
        jPanelAccount.setLayout(jPanelAccountLayout);
        jPanelAccountLayout.setHorizontalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAccountLayout.setVerticalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Account", jPanelAccount);

        javax.swing.GroupLayout jPanelFilesLayout = new javax.swing.GroupLayout(jPanelFiles);
        jPanelFiles.setLayout(jPanelFilesLayout);
        jPanelFilesLayout.setHorizontalGroup(
            jPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        jPanelFilesLayout.setVerticalGroup(
            jPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Files", jPanelFiles);

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("About", jPanelAbout);

        jButtonClose.setText("Close");
        jButtonClose.setMaximumSize(new java.awt.Dimension(97, 34));
        jButtonClose.setMinimumSize(new java.awt.Dimension(97, 34));
        jButtonClose.setPreferredSize(new java.awt.Dimension(97, 33));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthActionPerformed
        if (!GoogleDriveOAuth.isValidCredential()) {
            try {
                JOptionPane.showMessageDialog(this, "Your browser will be to open to perform authorization!", "Information", JOptionPane.INFORMATION_MESSAGE);
                GoogleDriveOAuth.authorize();
                jButtonDeleteAccount.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Authorization performed successfully!", "Sucessful", JOptionPane.INFORMATION_MESSAGE);
                getKey();
                if (driveController == null) {
                    driveController = new GoogleDriveController();
                }
                driveController.start();
                setAccountInfo();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "WARNING", JOptionPane.WARNING_MESSAGE);
                ex.printStackTrace();
            } catch (GeneralSecurityException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "WARNING", JOptionPane.WARNING_MESSAGE);
                ex.printStackTrace();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "WARNING", JOptionPane.WARNING_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "The application is already authorized!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAuthActionPerformed

    private void jCheckBoxEnableGoogleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxEnableGoogleItemStateChanged
        setConfigGoogleDriveAccount();
        getConfigGoogleDriveAccount();
    }//GEN-LAST:event_jCheckBoxEnableGoogleItemStateChanged

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAccountActionPerformed
        // TODO add your handling code here:
        int value = JOptionPane.showConfirmDialog(this, "Would you like to delete your Google Drive account this computer?", "Information", JOptionPane.YES_NO_OPTION);
        if (value == JOptionPane.YES_OPTION) {
            deleteGoogleAccount();
            JOptionPane.showMessageDialog(null, "Your Google Drive account was deleted this computer with success!", "Sucessful", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteAccountActionPerformed

    private void jButtonCopyKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyKeyActionPerformed
        if (GDUtils.SECRET_KEY.exists()) {
            saveKey();
        } else {
            JOptionPane.showMessageDialog(null, "Key not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCopyKeyActionPerformed

    private void getConfigGoogleDriveAccount() {
        Boolean enable = Boolean.valueOf(Config.readXMLConfig("enable-google-drive").getValue());
        Boolean enableAPIPersonal = Boolean.valueOf(Config.readXMLConfig("enable-api-personal").getValue());
        jCheckBoxEnableGoogle.setSelected(enable);
        jButtonAuth.setEnabled(enable);
        if (GoogleDriveOAuth.isValidCredential()) {
            jButtonCopyKey.setEnabled(enable);
            jButtonDeleteAccount.setEnabled(enable);
        } else {
            jButtonDeleteAccount.setEnabled(false);
        }
        setAccountInfo();
    }

    private void setConfigGoogleDriveAccount() {
        Config.readXMLConfig("enable-google-drive").setText(String.valueOf(jCheckBoxEnableGoogle.isSelected()));
//        Config.readXMLConfig("enable-api-personal").setText(String.valueOf(jCheckBoxEnablePersonal.isSelected()));
        Config.saveXMLConfig();
    }

    private void setAccountInfo() {
        jLabelName.setText(Config.readXMLConfig("google-name").getText());
        jLabelEmail.setText(Config.readXMLConfig("google-email").getText());
    }

    private void deleteGoogleAccount() {
        Config.readXMLConfig("enable-google-drive").setText("false");
        Config.readXMLConfig("enable-api-personal").setText("false");
        Config.readXMLConfig("google-name").setText("");
        Config.readXMLConfig("google-email").setText("");
        Config.saveXMLConfig();
        Config.deleteDir(GDUtils.STORE_CONFIG_GOOGLE_DRIVE);
        getConfigGoogleDriveAccount();
    }
    //    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        try {
//            /* Set the System look and feel */
//            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//             */
//            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (ClassNotFoundException ex) {
//            ex.printStackTrace();
//            Logger.getLogger(JFramePreferences.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            ex.printStackTrace();
//            Logger.getLogger(JFramePreferences.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            ex.printStackTrace();
//            Logger.getLogger(JFramePreferences.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            ex.printStackTrace();
//            Logger.getLogger(JFramePreferences.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//
//
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                JFramePreferences main = new JFramePreferences();
//                main.setLocationRelativeTo(null);
//                main.setVisible(false);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAuth;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCopyKey;
    private javax.swing.JButton jButtonDeleteAccount;
    private javax.swing.JCheckBox jCheckBoxEnableGoogle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelFiles;
    private javax.swing.JPanel jPanelGeneral2;
    private javax.swing.JPanel jPanelGoogleDrive;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPaneAccount;
    private javax.swing.JTextField jTextFieldDefaultLocation;
    // End of variables declaration//GEN-END:variables

    private void getKey() {
        int value = JOptionPane.showConfirmDialog(this, "Would you like to create a new key?", "Question", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == value) {
            try {
                KeyManager.generateKey();
                JOptionPane.showMessageDialog(this, "Your key was generated and saved in the  configuration directory of application!", "Successful", JOptionPane.INFORMATION_MESSAGE);
                int value1 = JOptionPane.showConfirmDialog(this, "Is recommended that you save your key in your smartphone using the application KeyManager \n"
                        + "Would you like to make this now?", "Information", JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION == value1){
                    saveKey();
                }else if(JOptionPane.NO_OPTION ==  value1){
                    
                }
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (KeyStoreException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (CertificateException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (NoSuchPaddingException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (InvalidKeyException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else if (JOptionPane.NO_OPTION == value) {
        }
    }

    private void saveKey() {
       //Criar metodo para enviar a chave para KeyManager ou salvar em outro local
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
